### ISSUE TITLE
Twitter developer app instructions are ambiguous.

### ISSUE THREAD

**Issue by jarulsamy** [jarulsamy/Twitter-Archive#19]
Currently the instructions for creating a new twitter developer account/project/app are somewhat vague and difficult to follow. Updating these instructions (maybe to their own dedicated file) would make using this app much easier.

**Comment by codetroll** [comment]
I am some what stalled as I seem to have to enter callback URLs to create the oauth 2 keys - what should these call back urls be?

**Comment by jarulsamy** [comment]
> I am some what stalled as I seem to have to enter callback URLs to create the oauth 2 keys - what should these call back urls be?

This totally slipped my mind, sorry about that. The callback URL is. `http://localhost:8080`.

I will add that in when the instructions are updated.

**Comment by codetroll** [comment]
Cheers - will give it a go!
