### ISSUE TITLE
twitter-archive: command not found

### ISSUE THREAD

**Issue by Smalls38** [jarulsamy/Twitter-Archive#20]
I'm quite new to all these things so I'm not sure what I did wrong. I have python 3.9 installed and everything in the requirement.txt. and I followed all the steps in the readme. But when I try to invoke the app it tells me that the command is not found.

**Comment by jarulsamy** [comment]
Which OS are you using? Try invoking the package through python itself like this:
```
$ python -m twitter-archive
```
If this works, you have the package correctly installed, but your `Python/Scripts` directory is not in your PATH.

**Comment by Smalls38** [comment]
Thank you for the reply, I used both Windows and Ubuntu for this project. I found the problem was that I had to change the directory to the Twitter-Archive folder and do "python3 twitter-archive" in the command prompt.
