### ISSUE TITLE
Twitter Something Went Wrong

### ISSUE THREAD

**Issue by Smalls38** [jarulsamy/Twitter-Archive#21]
I couldn't figure out what exactly I did wrong. I couldn't figure out how to grant the scopes from the readme because I don't know where to find them, and I don't know what URL to put for the "website URL" in the user authentication settings.

**Comment by Smalls38** [comment]
When I clicked on the link from the CLI I got a Twitter page saying 

Something went Wrong
You weren't able to give access to the App. Go back and try logging in again.

**Comment by Jaid** [comment]
Works for me in v0.0.8. My callback goes to `http://localhost:8080`.

**Comment by jarulsamy** [comment]
> I couldn't figure out what exactly I did wrong. I couldn't figure out how to grant the scopes from the readme because I don't know where to find them, and I don't know what URL to put for the "website URL" in the user authentication settings.

I've updated the instructions, although I am unsure if they are really too helpful. Unfortunately Twitter doesn't let me delete my existing project so I can't go through the setup again to make better instructions. Someone going through this for the first time would be better suited to writing the documentation for this. For the time being, I will mark this as closed. But better instructions / docs are probably still needed.
